# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html

minecraft_version=26.1-snapshot-1
loader_version=0.18.3
ae2_version=15.0.3-alpha
jei_version=19.21.0.247
rei_version=16.0.788

# Mod Properties
mod_version=1.5.0-26.1-snapshot-1-Fabric
forge_mod_version=1.4.15-26.1-snapshot-1-Forge
neoforge_mod_version=1.4.15-26.1-snapshot-1-NeoForge
maven_group=com.skniro
archives_base_name=Maple
mod_author=skniro
# Dependencies
# check this on https://modmuss50.me/fabric.html
#Fabric api
fabric_version=0.140.1+26.1
forge_version=61.0.2
forge_version_range=[46,)
terrablender_version=26.1-snapshot-1-21.11.0.0

# Neoforge Properties
minecraft_version_range=[26.0,26.2)
mod_id=maple
mod_name=Maple
mod_license=Creative Commons Attribution-ShareAlike 4.0 International
mod_group_id=com.skniro.maple
mod_description=
mod_authors=skniro

# Neoforge
neo_version=26.1.0.0-alpha.2+snapshot-1
neo_version_range=[26.1.0.0-alpha,)
loader_version_range=[2,)







