modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="maple"
version="${forge_mod_version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${mod_description}'''

[[mixins]]
config="maple.mixins.json"

[[dependencies.maple]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.maple]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.maple]]
modId = "terrablender"
mandatory = true
versionRange = "[2.0.1.136,)"
ordering = "NONE"
side = "BOTH"
