package com.skniro.maple.datagen;

import com.skniro.maple.block.*;
import com.skniro.maple.item.MapleItems;
import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Blocks;
import net.minecraft.block.CropBlock;
import net.minecraft.item.ItemConvertible;
import net.minecraft.item.Items;
import net.minecraft.loot.condition.BlockStatePropertyLootCondition;
import net.minecraft.loot.entry.ItemEntry;
import net.minecraft.loot.function.SetCountLootFunction;
import net.minecraft.loot.provider.number.UniformLootNumberProvider;


public class MapleLootTableGenerator extends FabricBlockLootTableProvider {
    public MapleLootTableGenerator(FabricDataOutput dataGenerator) {
        super(dataGenerator);
    }
    public static final float[] SAPLING_DROP_CHANCE = new float[]{0.048F, 0.0425F, 0.062333336F, 0.1F};

    @Override
    public void generate() {
        //CHERRY
        addDrop(MapleSignBlocks.CHERRY_SIGN);
        addDrop(MapleSignBlocks.CHERRY_WALL_SIGN);
        addDrop(MapleBlocks.CHERRY_LOG);
        addDrop(MapleBlocks.CHERRY_WOOD);
        addDrop(MapleBlocks.CHERRY_DOOR,doorDrops(MapleBlocks.CHERRY_DOOR));
        addDrop(MapleBlocks.CHERRY_SAPLING);
        addDrop(MapleBlocks.CHERRY_LEAVES,leavesDrops(MapleBlocks.CHERRY_LEAVES,MapleBlocks.CHERRY_SAPLING,SAPLING_DROP_CHANCE));
        addDrop(MapleBlocks.CHERRY_BUTTON);
        addDrop(MapleBlocks.CHERRY_FENCE);
        addDrop(MapleBlocks.CHERRY_FENCE_GATE);
        addDrop(MapleBlocks.CHERRY_PLANKS);
        addDrop(MapleBlocks.CHERRY_PRESSURE_PLATE);
        addDrop(MapleBlocks.CHERRY_SLAB);
        addDrop(MapleBlocks.CHERRY_STAIRS);
        addDrop(MapleBlocks.CHERRY_TRAPDOOR);
        addDrop(MapleBlocks.STRIPPED_CHERRY_LOG);
        addDrop(MapleBlocks.STRIPPED_CHERRY_WOOD);

        //MAPLE
        addDrop(MapleSignBlocks.Maple_SIGN);
        addDrop(MapleSignBlocks.Maple_WALL_SIGN);
        addDrop(MapleSignBlocks.Maple_HANGING_SIGN);
        addDrop(MapleSignBlocks.Maple_WALL_HANGING_SIGN);
        addDrop(MapleBlocks.MAPLE_LOG);
        addDrop(MapleBlocks.MAPLE_WOOD);
        addDrop(MapleBlocks.MAPLE_DOOR,doorDrops(MapleBlocks.MAPLE_DOOR));
        addDrop(MapleBlocks.MAPLE_SAPLING);
        addDrop(MapleBlocks.RED_MAPLE_SAPLING);
        addDrop(MapleBlocks.MAPLE_LEAVES,leavesDrops(MapleBlocks.MAPLE_LEAVES,MapleBlocks.MAPLE_SAPLING,SAPLING_DROP_CHANCE));
        addDrop(MapleBlocks.RED_MAPLE_LEAVES,leavesDrops(MapleBlocks.RED_MAPLE_LEAVES,MapleBlocks.RED_MAPLE_SAPLING,SAPLING_DROP_CHANCE));
        addDrop(MapleBlocks.MAPLE_BUTTON);
        addDrop(MapleBlocks.MAPLE_FENCE);
        addDrop(MapleBlocks.MAPLE_FENCE_GATE);
        addDrop(MapleBlocks.MAPLE_PLANKS);
        addDrop(MapleBlocks.MAPLE_PRESSURE_PLATE);
        addDrop(MapleBlocks.MAPLE_SLAB);
        addDrop(MapleBlocks.MAPLE_STAIRS);
        addDrop(MapleBlocks.MAPLE_TRAPDOOR);
        addDrop(MapleBlocks.STRIPPED_MAPLE_LOG);
        addDrop(MapleBlocks.STRIPPED_MAPLE_WOOD);

        //GINKGO
        addDrop(MapleSignBlocks.GINKGO_SIGN);
        addDrop(MapleSignBlocks.GINKGO_WALL_SIGN);
        addDrop(MapleSignBlocks.GINKGO_HANGING_SIGN);
        addDrop(MapleSignBlocks.GINKGO_WALL_HANGING_SIGN);
        addDrop(MapleBlocks.GINKGO_LOG);
        addDrop(MapleBlocks.GINKGO_WOOD);
        addDrop(MapleBlocks.GINKGO_DOOR,doorDrops(MapleBlocks.GINKGO_DOOR));
        addDrop(MapleBlocks.GINKGO_LEAVES,leavesDrops(MapleBlocks.GINKGO_LEAVES,MapleBlocks.GINKGO_SAPLING,SAPLING_DROP_CHANCE));
        addDrop(MapleBlocks.GINKGO_BUTTON);
        addDrop(MapleBlocks.GINKGO_FENCE);
        addDrop(MapleBlocks.GINKGO_FENCE_GATE);
        addDrop(MapleBlocks.GINKGO_PLANKS);
        addDrop(MapleBlocks.GINKGO_PRESSURE_PLATE);
        addDrop(MapleBlocks.GINKGO_SLAB);
        addDrop(MapleBlocks.GINKGO_STAIRS);
        addDrop(MapleBlocks.GINKGO_TRAPDOOR);
        addDrop(MapleBlocks.GINKGO_SAPLING);
        addDrop(MapleBlocks.STRIPPED_GINKGO_LOG);
        addDrop(MapleBlocks.STRIPPED_GINKGO_WOOD);




        //BAMBOO
        addDrop(MapleBlocks.BAMBOO_BLOCK);
        addDrop(MapleSignBlocks.BAMBOO_SIGN);
        addDrop(MapleSignBlocks.BAMBOO_WALL_SIGN);
        addDrop(MapleBlocks.BAMBOO_MOSAIC);
        addDrop(MapleBlocks.BAMBOO_DOOR,doorDrops(MapleBlocks.BAMBOO_DOOR));
        addDrop(MapleBlocks.BAMBOO_BUTTON);
        addDrop(MapleBlocks.BAMBOO_FENCE);
        addDrop(MapleBlocks.BAMBOO_FENCE_GATE);
        addDrop(MapleBlocks.BAMBOO_PLANKS);
        addDrop(MapleBlocks.BAMBOO_PRESSURE_PLATE);
        addDrop(MapleBlocks.BAMBOO_SLAB);
        addDrop(MapleBlocks.BAMBOO_STAIRS);
        addDrop(MapleBlocks.BAMBOO_MOSAIC_SLAB);
        addDrop(MapleBlocks.BAMBOO_MOSAIC_STAIRS);
        addDrop(MapleBlocks.BAMBOO_TRAPDOOR);
        addDrop(MapleBlocks.STRIPPED_BAMBOO_BLOCK);

        //SAKURA
        addDrop(MapleBlocks.SAKURA_SAPLING);
        addDrop(MapleBlocks.SAKURA_LEAVES, leavesDrops(MapleBlocks.SAKURA_LEAVES,MapleBlocks.SAKURA_SAPLING, SAPLING_DROP_CHANCE));

        //Crop
        net.minecraft.loot.condition.LootCondition.Builder builder = BlockStatePropertyLootCondition.builder(MapleBlocks.RICE).properties(net.minecraft.predicate.StatePredicate.Builder.create().exactMatch(CropBlock.AGE, 7));
        addDrop(MapleBlocks.RICE, cropDrops(MapleBlocks.RICE, MapleItems.SOYBEAN,MapleItems.Rice,builder));

        //Glass Block
        addDropWithSilkTouch(MapleBlocks.WHITE_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.WHITE_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.ORANGE_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.ORANGE_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.YELLOW_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.YELLOW_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.LIME_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.LIME_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.PINK_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.PINK_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.GRAY_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.GRAY_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.CYAN_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.CYAN_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.PURPLE_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.PURPLE_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.BLUE_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.BLUE_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.BROWN_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.BROWN_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.GREEN_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.GREEN_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.RED_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.RED_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.BLACK_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.BLACK_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.GLASS_STAIRS);

        addDrop(MapleBlocks.TATAMI);
        addDrop(MapleBlocks.TATAMI_SLAB);

        addDrop(MapleNetherOresBlocks.Nether_Coal_Ore, oreDrops(MapleNetherOresBlocks.Nether_Coal_Ore, Items.COAL));
        addDrop(MapleNetherOresBlocks.Nether_Copper_Ore, copperOreDrops(MapleNetherOresBlocks.Nether_Copper_Ore));
        addDrop(MapleNetherOresBlocks.Nether_Diamond_Ore, oreDrops(MapleNetherOresBlocks.Nether_Diamond_Ore,Items.DIAMOND));
        addDrop(MapleNetherOresBlocks.Nether_Emerald_Ore, oreDrops(MapleNetherOresBlocks.Nether_Emerald_Ore,Items.EMERALD));
        addDrop(MapleNetherOresBlocks.Nether_Gold_Ore, oreDrops(MapleNetherOresBlocks.Nether_Gold_Ore,Items.RAW_GOLD));
        addDrop(MapleNetherOresBlocks.Nether_Iron_Ore, oreDrops(MapleNetherOresBlocks.Nether_Iron_Ore,Items.RAW_IRON));
        addDrop(MapleNetherOresBlocks.Nether_Lapis_Ore, lapisOreDrops(MapleNetherOresBlocks.Nether_Lapis_Ore));
        addDrop(MapleNetherOresBlocks.Nether_Redstone_Ore,redstoneOreDrops(MapleNetherOresBlocks.Nether_Redstone_Ore));
        addDrop(MapleNetherOresBlocks.Nether_Coal_Ore, oreDrops(MapleNetherOresBlocks.Nether_Coal_Ore,Items.COAL));
        addDrop(MapleOreBlocks.Salt_Ore, dropsWithSilkTouch(MapleOreBlocks.Salt_Ore, this.applyExplosionDecay(MapleOreBlocks.Salt_Ore, ItemEntry.builder(MapleItems.Salt).apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1.0F,1.0F))))));
        addDrop(MapleOreBlocks.DEEPSLATE_Salt_Ore, dropsWithSilkTouch(MapleOreBlocks.DEEPSLATE_Salt_Ore, this.applyExplosionDecay(MapleOreBlocks.DEEPSLATE_Salt_Ore, ItemEntry.builder(MapleItems.Salt).apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2.0F, 5.0F))))));

        addDrop(MapleBlocks.RED_MAPLE_CARPET);
        addDrop(MapleBlocks.Maple_CARPET);
        addDrop(MapleBlocks.GINKGO_CARPET);
        addDrop(MapleBlocks.SAKURA_CARPET);

        //PLASTER
        addDrop(MapleBlocks.GREEN_PLASTER);
        addDrop(MapleBlocks.PLASTER);
        addDrop(MapleBlocks.ORANGE_PLASTER);
        addDrop(MapleBlocks.MAGENTA_PLASTER);
        addDrop(MapleBlocks.LIGHT_BLUE_PLASTER);
        addDrop(MapleBlocks.YELLOW_PLASTER);
        addDrop(MapleBlocks.LIME_PLASTER);
        addDrop(MapleBlocks.PINK_PLASTER);
        addDrop(MapleBlocks.GRAY_PLASTER);
        addDrop(MapleBlocks.LIGHT_GRAY_PLASTER);
        addDrop(MapleBlocks.CYAN_PLASTER);
        addDrop(MapleBlocks.PURPLE_PLASTER);
        addDrop(MapleBlocks.BLUE_PLASTER);
        addDrop(MapleBlocks.BROWN_PLASTER);
        addDrop(MapleBlocks.RED_PLASTER);

        //Sea Lantern
        addDrop(MapleBlocks.Iron_Sea_Lantern);
        addDrop(MapleBlocks.Gold_Sea_Lantern);

        //Potted
        addPottedPlantDrops(MapleBlocks.POTTED_SAKURA_SAPLING);
        addPottedPlantDrops(MapleBlocks.POTTED_RED_MAPLE_SAPLING);
        addPottedPlantDrops(MapleBlocks.POTTED_CHERRY_SAPLING);
        addPottedPlantDrops(MapleBlocks.POTTED_GINKGO_SAPLING);
        addPottedPlantDrops(MapleBlocks.POTTED_MAPLE_SAPLING);

        //Cushion
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_WHITE);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_ORANGE);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_MAGENTA);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_LIGHT_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_YELLOW);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_LIME);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_PINK);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_LIGHT_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_CYAN);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_PURPLE);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_BROWN);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_GREEN);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_RED);
        addDrop(MapleFurnitureBlocks.CUSHION_OAK_BLACK);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_WHITE);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_ORANGE);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_MAGENTA);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_LIGHT_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_YELLOW);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_LIME);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_PINK);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_LIGHT_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_CYAN);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_PURPLE);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_BROWN);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_GREEN);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_RED);
        addDrop(MapleFurnitureBlocks.CUSHION_SPRUCE_BLACK);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_WHITE);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_ORANGE);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_MAGENTA);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_LIGHT_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_YELLOW);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_LIME);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_PINK);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_LIGHT_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_CYAN);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_PURPLE);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_BROWN);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_GREEN);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_RED);
        addDrop(MapleFurnitureBlocks.CUSHION_BIRCH_BLACK);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_WHITE);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_ORANGE);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_MAGENTA);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_LIGHT_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_YELLOW);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_LIME);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_PINK);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_LIGHT_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_CYAN);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_PURPLE);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_BROWN);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_GREEN);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_RED);
        addDrop(MapleFurnitureBlocks.CUSHION_JUNGLE_BLACK);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_WHITE);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_ORANGE);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_MAGENTA);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_LIGHT_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_YELLOW);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_LIME);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_PINK);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_LIGHT_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_CYAN);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_PURPLE);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_BROWN);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_GREEN);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_RED);
        addDrop(MapleFurnitureBlocks.CUSHION_ACACIA_BLACK);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_WHITE);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_ORANGE);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_MAGENTA);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_LIGHT_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_YELLOW);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_LIME);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_PINK);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_LIGHT_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_CYAN);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_PURPLE);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_BROWN);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_GREEN);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_RED);
        addDrop(MapleFurnitureBlocks.CUSHION_DARK_OAK_BLACK);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_WHITE);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_ORANGE);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_MAGENTA);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_LIGHT_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_YELLOW);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_LIME);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_PINK);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_LIGHT_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_CYAN);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_PURPLE);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_BROWN);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_GREEN);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_RED);
        addDrop(MapleFurnitureBlocks.CUSHION_CRIMSON_BLACK);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_WHITE);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_ORANGE);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_MAGENTA);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_LIGHT_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_YELLOW);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_LIME);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_PINK);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_LIGHT_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_CYAN);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_PURPLE);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_BROWN);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_GREEN);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_RED);
        addDrop(MapleFurnitureBlocks.CUSHION_WARPED_BLACK);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_WHITE);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_ORANGE);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_MAGENTA);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_LIGHT_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_YELLOW);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_LIME);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_PINK);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_LIGHT_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_CYAN);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_PURPLE);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_BROWN);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_GREEN);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_RED);
        addDrop(MapleFurnitureBlocks.CUSHION_MANGROVE_BLACK);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_WHITE);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_ORANGE);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_MAGENTA);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_LIGHT_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_YELLOW);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_LIME);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_PINK);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_LIGHT_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_CYAN);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_PURPLE);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_BROWN);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_GREEN);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_RED);
        addDrop(MapleFurnitureBlocks.CUSHION_CHERRY_BLACK);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_WHITE);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_ORANGE);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_MAGENTA);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_LIGHT_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_YELLOW);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_LIME);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_PINK);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_LIGHT_GRAY);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_CYAN);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_PURPLE);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_BLUE);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_BROWN);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_GREEN);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_RED);
        addDrop(MapleFurnitureBlocks.CUSHION_BAMBOO_BLACK);

        addDrop(MapleFurnitureBlocks.TABLE_OAK);
        addDrop(MapleFurnitureBlocks.TABLE_SPRUCE);
        addDrop(MapleFurnitureBlocks.TABLE_BIRCH);
        addDrop(MapleFurnitureBlocks.TABLE_JUNGLE);
        addDrop(MapleFurnitureBlocks.TABLE_ACACIA);
        addDrop(MapleFurnitureBlocks.TABLE_DARK_OAK);
        addDrop(MapleFurnitureBlocks.TABLE_CRIMSON);
        addDrop(MapleFurnitureBlocks.TABLE_WARPED);
        addDrop(MapleFurnitureBlocks.TABLE_MANGROVE);
        addDrop(MapleFurnitureBlocks.TABLE_BAMBOO);
        addDrop(MapleFurnitureBlocks.TABLE_CHERRY);

        //CoffeeTable
        addDrop(MapleFurnitureBlocks.Coffee_Table_WOOD_OAK);
        addDrop(MapleFurnitureBlocks.Coffee_Table_WOOD_SPRUCE);
        addDrop(MapleFurnitureBlocks.Coffee_Table_WOOD_BIRCH);
        addDrop(MapleFurnitureBlocks.Coffee_Table_WOOD_JUNGLE);
        addDrop(MapleFurnitureBlocks.Coffee_Table_WOOD_ACACIA);
        addDrop(MapleFurnitureBlocks.Coffee_Table_WOOD_DARK_OAK);
        addDrop(MapleFurnitureBlocks.Coffee_Table_WOOD_CRIMSON);
        addDrop(MapleFurnitureBlocks.Coffee_Table_WOOD_WARPED);
        addDrop(MapleFurnitureBlocks.Coffee_Table_WOOD_MANGROVE);
        addDrop(MapleFurnitureBlocks.Coffee_Table_WOOD_BAMBOO);
        addDrop(MapleFurnitureBlocks.Coffee_Table_WOOD_CHERRY);
        addDrop(MapleFurnitureBlocks.Coffee_Table_PLANK_OAK);
        addDrop(MapleFurnitureBlocks.Coffee_Table_PLANK_SPRUCE);
        addDrop(MapleFurnitureBlocks.Coffee_Table_PLANK_BIRCH);
        addDrop(MapleFurnitureBlocks.Coffee_Table_PLANK_JUNGLE);
        addDrop(MapleFurnitureBlocks.Coffee_Table_PLANK_ACACIA);
        addDrop(MapleFurnitureBlocks.Coffee_Table_PLANK_DARK_OAK);
        addDrop(MapleFurnitureBlocks.Coffee_Table_PLANK_CRIMSON);
        addDrop(MapleFurnitureBlocks.Coffee_Table_PLANK_WARPED);
        addDrop(MapleFurnitureBlocks.Coffee_Table_PLANK_MANGROVE);
        addDrop(MapleFurnitureBlocks.Coffee_Table_PLANK_BAMBOO);
        addDrop(MapleFurnitureBlocks.Coffee_Table_PLANK_CHERRY);

        //Chair
        addDrop(MapleFurnitureBlocks.Chair_WOOD_OAK);
        addDrop(MapleFurnitureBlocks.Chair_WOOD_SPRUCE);
        addDrop(MapleFurnitureBlocks.Chair_WOOD_BIRCH);
        addDrop(MapleFurnitureBlocks.Chair_WOOD_JUNGLE);
        addDrop(MapleFurnitureBlocks.Chair_WOOD_ACACIA);
        addDrop(MapleFurnitureBlocks.Chair_WOOD_DARK_OAK);
        addDrop(MapleFurnitureBlocks.Chair_WOOD_CRIMSON);
        addDrop(MapleFurnitureBlocks.Chair_WOOD_WARPED);
        addDrop(MapleFurnitureBlocks.Chair_WOOD_MANGROVE);
        addDrop(MapleFurnitureBlocks.Chair_WOOD_BAMBOO);
        addDrop(MapleFurnitureBlocks.Chair_WOOD_CHERRY);
        addDrop(MapleFurnitureBlocks.Chair_PLANK_OAK);
        addDrop(MapleFurnitureBlocks.Chair_PLANK_SPRUCE);
        addDrop(MapleFurnitureBlocks.Chair_PLANK_BIRCH);
        addDrop(MapleFurnitureBlocks.Chair_PLANK_JUNGLE);
        addDrop(MapleFurnitureBlocks.Chair_PLANK_ACACIA);
        addDrop(MapleFurnitureBlocks.Chair_PLANK_DARK_OAK);
        addDrop(MapleFurnitureBlocks.Chair_PLANK_CRIMSON);
        addDrop(MapleFurnitureBlocks.Chair_PLANK_WARPED);
        addDrop(MapleFurnitureBlocks.Chair_PLANK_MANGROVE);
        addDrop(MapleFurnitureBlocks.Chair_PLANK_BAMBOO);
        addDrop(MapleFurnitureBlocks.Chair_PLANK_CHERRY);

        addDrop(MapleFurnitureBlocks.END_TABLE_OAK);
        addDrop(MapleFurnitureBlocks.END_TABLE_SPRUCE);
        addDrop(MapleFurnitureBlocks.END_TABLE_BIRCH);
        addDrop(MapleFurnitureBlocks.END_TABLE_JUNGLE);
        addDrop(MapleFurnitureBlocks.END_TABLE_ACACIA);
        addDrop(MapleFurnitureBlocks.END_TABLE_DARK_OAK);
        addDrop(MapleFurnitureBlocks.END_TABLE_CRIMSON);
        addDrop(MapleFurnitureBlocks.END_TABLE_WARPED);
        addDrop(MapleFurnitureBlocks.END_TABLE_MANGROVE);
        addDrop(MapleFurnitureBlocks.END_TABLE_BAMBOO);
        addDrop(MapleFurnitureBlocks.END_TABLE_CHERRY);

        addDrop(MapleFurnitureBlocks.Window_WOOD_OAK);
        addDrop(MapleFurnitureBlocks.Window_WOOD_BIRCH);
        addDrop(MapleFurnitureBlocks.Window_WOOD_SPRUCE);
        addDrop(MapleFurnitureBlocks.Window_WOOD_JUNGLE);
        addDrop(MapleFurnitureBlocks.Window_WOOD_DARK_OAK);
        addDrop(MapleFurnitureBlocks.Window_WOOD_ACACIA);
        addDrop(MapleFurnitureBlocks.Window_WOOD_MANGROVE);
        addDrop(MapleFurnitureBlocks.Window_WOOD_CHERRY);
        addDrop(MapleFurnitureBlocks.Window_WOOD_CRIMSON);
        addDrop(MapleFurnitureBlocks.Window_WOOD_WARPED);
        addDrop(MapleFurnitureBlocks.Window_PLANK_OAK);
        addDrop(MapleFurnitureBlocks.Window_PLANK_BIRCH);
        addDrop(MapleFurnitureBlocks.Window_PLANK_SPRUCE);
        addDrop(MapleFurnitureBlocks.Window_PLANK_JUNGLE);
        addDrop(MapleFurnitureBlocks.Window_PLANK_DARK_OAK);
        addDrop(MapleFurnitureBlocks.Window_PLANK_ACACIA);
        addDrop(MapleFurnitureBlocks.Window_PLANK_MANGROVE);
        addDrop(MapleFurnitureBlocks.Window_PLANK_CHERRY);
        addDrop(MapleFurnitureBlocks.Window_PLANK_CRIMSON);
        addDrop(MapleFurnitureBlocks.Window_PLANK_WARPED);

    }
}
